---
#version: "3.1"
#services:
#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    network_mode: host
#    environment:
#      - PUID=${UID}
#      - PGID=13000
#      - VERSION=docker
#      - PLEX_CLAIM=${PLEX_CLAIM}
#    volumes:
#      - ${ROOT_DIR}/docker/plex-config:/config
#      - ${ROOT_DIR}/data/media:/data/media
#    ports:
#      - 32400:32400
#    restart: unless-stopped



version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=1000
      - VERSION=docker
#      - PLEX_CLAIM= #optional
    volumes:
      - ${ROOT_DIR}/library:/config
      - ${ROOT_DIR}/tvseries:/tv
      - ${ROOT_DIR}/movies:/movies
    ports:
      - 32400:32400
    restart: unless-stopped    

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=13000
      - EST=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/tautulli-config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - EST=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/jellyfin-config:/config
      - ${ROOT_DIR}/data/media:/data/media
    ports:
      - 8096:8096
    restart: unless-stopped

#
# SERVARR
#
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - EST=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/radarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - EST=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/sonarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - EST=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/readarr-config:/config
      - ${ROOT_DIR}/data:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - EST=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped



version: "2.1"
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${ROOT_DIR}/deluge/config:/config
      - ${ROOT_DIR}/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped



version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${ROOT_DIR}/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped